version: "3"
services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "4001:4000"
    environment:
      - DATABASE_URL=postgresql://jiaqilisit722part3_fbqi_user:KjORnFJIwBshwGtswFVvjCmcMVw5wlX4@dpg-cs1je35ds78s73b6tpn0-a.oregon-postgres.render.com/jiaqilisit722part3_fbqi
    restart: "no"
  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "4002:4000"
    environment:
      - DATABASE_URL=postgresql://jiaqilisit722part3_fbqi_user:KjORnFJIwBshwGtswFVvjCmcMVw5wlX4@dpg-cs1je35ds78s73b6tpn0-a.oregon-postgres.render.com/jiaqilisit722part3_fbqi
    restart: "no"