apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: jiaqilisit722part3.azurecr.io/book_catalog:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          value: "postgresql://jiaqilisit722part3_fbqi_user:KjORnFJIwBshwGtswFVvjCmcMVw5wlX4@dpg-cs1je35ds78s73b6tpn0-a.oregon-postgres.render.com/jiaqilisit722part3_fbqi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: jiaqilisit722part3.azurecr.io/inventory_management:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          value: "postgresql://jiaqilisit722part3_fbqi_user:KjORnFJIwBshwGtswFVvjCmcMVw5wlX4@dpg-cs1je35ds78s73b6tpn0-a.oregon-postgres.render.com/jiaqilisit722part3_fbqi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000